version: '3'
networks:
  default:
    external:
      name: proto1_swarm

services:
  gateway:
    image: gateway:jvm
    deploy:
      replicas: 1
    ports:
      - "8080:8080"

  order-microservice:
    image: order-microservice:jvm
    deploy:
      replicas: 1
    ports:
      - "8081:8080"

  product-microservice:
    image: product-microservice:jvm
    deploy:
      replicas: 1
    ports:
      - "8082:8080"

  dueout-microservice:
    image: dueout-microservice:jvm
    deploy:
      replicas: 1
    ports:
      - "8083:8080"



