version: '3'
networks:
  default:
    external:
      name: proto1_swarm

services:
  gateway:
    image: gateway:fast
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
      - "5080:5005"
    environment:
      - JAVA_ENABLE_DEBUG="true"

  order-microservice:
    image: order-microservice:fast
    deploy:
      replicas: 1
    ports:
      - "8081:8080"
      - "5081:5005"
    environment:
      - JAVA_ENABLE_DEBUG="true"

  product-microservice:
    image: product-microservice:fast
    deploy:
      replicas: 1
    ports:
      - "8082:8080"
      - "5082:5005"
    environment:
      - JAVA_ENABLE_DEBUG="true"

  dueout-microservice:
    image: dueout-microservice:fast
    deploy:
      replicas: 1
    ports:
      - "8083:8080"
      - "5083:5005"
    environment:
      - JAVA_ENABLE_DEBUG="true"



