kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/gateway
  uid: f68c79f5-b4aa-4f11-8c40-07228a1fdbcd
  resourceVersion: '294489'
  generation: 3
  creationTimestamp: '2020-09-08T10:26:13Z'
  labels:
    com.docker.service.id: proto1-gateway
    com.docker.service.name: gateway
    com.docker.stack.namespace: proto1
  annotations:
    com.docker.stack.expected-generation: '3'
    deployment.kubernetes.io/revision: '1'
  ownerReferences:
    - apiVersion: compose.docker.com/v1alpha3
      kind: Stack
      name: proto1
      uid: 4a927d1e-5c3e-409f-a26b-cb9ae3d7220b
      controller: true
      blockOwnerDeletion: true
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.service.id: proto1-gateway
      com.docker.service.name: gateway
      com.docker.stack.namespace: proto1
  template:
    metadata:
      creationTimestamp: null
      labels:
        com.docker.service.id: proto1-gateway
        com.docker.service.name: gateway
        com.docker.stack.namespace: proto1
    spec:
      containers:
        - name: gateway
          image: gateway
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-09-08T10:26:17Z'
      lastTransitionTime: '2020-09-08T10:26:17Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-09-08T10:26:17Z'
      lastTransitionTime: '2020-09-08T10:26:13Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "gateway-76c86b775b" has successfully progressed.
