global:
   scrape_interval: 15s

  external_labels:
    monitor: 'something'

scrape_configs:
  - job_name: 'proto1'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['proto1:8080']
